server:
  port: ${PORT:8080}
  servlet:
    context-path: "/api/v1"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

application:
  jwt:
    secret-key: xxxxx
    login-expire-length: 86400000
    reset-password-expire-length: 60000

spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Africa/Lagos